### PR TITLE
create debug msgs

### PR DESCRIPTION
**Pull request by satoshi-ota**
- autoware_auto_debug_msgsの作成
- idl形式への書き換えは未実施

### CODE REVIEW

**Comment by takayuki5168** [comment]
@satoshi-ota idlではなくmsgなのでコピペしてきただけ？

**Comment by kenji-miyake** [comment]
@satoshi-ota Thank you, but it's better to use [git filter-repo](https://github.com/newren/git-filter-repo) to keep the original git history! :smile:

**Comment by satoshi-ota** [comment]
@takayuki5168 Yes, but I've completed the conversion to idl styles from msg in my local environment.

@kenji-miyake Thank you for your advice :+1: I'm going to check it out.

**Comment by yukkysaito** [comment]
@satoshi-ota とりあえずクイックなコメント！
一旦auto_msgsには追加せず、このままiv_msgsとして今回は扱う方針です 🙏

**Comment by yukkysaito** [comment]
https://tier4.atlassian.net/wiki/spaces/ATWROSS/pages/edit-v2/2157348027

**Comment by kenji-miyake** [comment]
@satoshi-ota I'm sorry for confusing you. As Saito-san says we'll keep debug msgs in iv_msgs and will consider whether to port debug msgs (and other things) to autoware_auto_msgs after the first integration has been done.

**Comment by satoshi-ota** [comment]
@kenji-miyake @yukkysaito OK, I understand. :+1: Then, I'll close this Pull Request.

**Pull request closed without merging**
