### PR TITLE
feat: add neutral mode to gear msgs

### PR DESCRIPTION
**Pull request by taikitanaka3**
# Description
add neutral command for gear msgs

in some situation NUETRAL message is necessary. 

https://star4.slack.com/archives/GRUE57C30/p1640070272320000?thread_ts=1640067609.307000&cid=GRUE57C30

# Related Issue
https://github.com/autowarefoundation/autoware.universe/issues/1

### CODE REVIEW

**Comment by tkimura4** [comment]
I think it's better to avoid to use "0" value.

**Comment by taikitanaka3** [comment]
fix enum according to this change
https://gitlab.com/autowarefoundation/autoware.auto/autoware_auto_msgs/-/merge_requests/70/diffs

it looks like gear command .auto is also changed

**Comment by yukkysaito** [comment]
Has this been discussed with the AWF side? Is there any chance that it can be merged with the original?

**Comment by taikitanaka3** [comment]
@yukkysaito 
If this PR is merged then this PR is same as .auto message type cc: @mitsudome-r 
https://gitlab.com/autowarefoundation/autoware.auto/autoware_auto_msgs/-/merge_requests/70

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
