### PR TITLE
feat(autoware_auto_perception_msgs): Add traffic light occlusion msgs

### PR DESCRIPTION
**Pull request by Mingyu1991**
Two messages are added in this PR for transferring traffic light occlusion ratios within perception nodes.

### CODE REVIEW

**Comment by yukkysaito** [comment]
I feel that this Interface is not necessary, but I would like to discuss it with you.

**Comment by Mingyu1991** [comment]
> I feel that this Interface is not necessary, but I would like to discuss it with you.

@yukkysaito 
I also feel this message is very simple and hope to replace it with some ros built-in messages,
but I couldn't find any suitable message.
Do you have any suggestion on which message to use?

**Comment by miursh** [comment]
@yukkysaito I talked with @Mingyu1991 , the reason why he add this extra msg, is because he want to separate the occlusion node from the classifier node and run it on the main ecu in order to avoid large network traffic (to send pointcloud topic to the edge ecu)

**Comment by Mingyu1991** [comment]
Close this PR since the new traffic_light_occlusion_predictor package don't need this IF anymore

**Pull request closed without merging**
